# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# IntelliJ IDEA is not yet fully compatible with configuration cache; keep it disabled for Loom.
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT
fabric_kotlin_version=1.13.11+kotlin.2.3.21

# Mod Properties
mod_version=1.0.1
maven_group=goldenrose01.enchlib
archives_base_name=enchlib

# Dependencies
fabric_api_version=0.148.0+26.2
kotlin_version=2.3.21
kotlinx_serialization_version=1.10.0
kotlinx_coroutines_version=1.10.2
